#!/usr/bin/env python3
"""
Compare two CoPerception summary JSON files (with Konro vs without Konro).

Expected JSON structure (generated by test_codet_network.py):
{
  "run": {...},
  "network": {...},
  "proxy": {...}
}
"""

import argparse
import json
import math
from pathlib import Path
from typing import Any, Dict, List, Tuple

try:
    import matplotlib.pyplot as plt  # type: ignore
except Exception:
    plt = None


def _read_json(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _select_run_entry(data: Dict[str, Any], run_index: int) -> Dict[str, Any]:
    """Return a single run payload from either legacy or history JSON format."""
    if isinstance(data, dict) and isinstance(data.get("runs"), list):
        runs = data["runs"]
        if not runs:
            raise ValueError("History file has no runs")
        try:
            selected = runs[run_index]
        except IndexError as exc:
            raise ValueError(
                f"Invalid run index {run_index} for history of length {len(runs)}"
            ) from exc
        if not isinstance(selected, dict):
            raise ValueError("Selected run entry is not a JSON object")
        return selected
    return data


def _get_num(d: Dict[str, Any], section: str, key: str) -> float:
    value = d.get(section, {}).get(key, 0.0)
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def _delta(with_k: float, without_k: float) -> Tuple[float, float]:
    diff = with_k - without_k
    if abs(without_k) < 1e-12:
        pct = math.inf if abs(diff) > 1e-12 else 0.0
    else:
        pct = (diff / without_k) * 100.0
    return diff, pct


def _fmt_pct(p: float) -> str:
    if math.isinf(p):
        return "inf"
    return f"{p:+.2f}%"


def _fmt_val(v: float) -> str:
    if abs(v) >= 1000:
        return f"{v:,.3f}"
    return f"{v:.6f}"


def _print_table(rows: List[Tuple[str, float, float, bool]]) -> None:
    # rows = (metric_name, with_konro, without_konro, higher_is_better)
    headers = [
        "Metric",
        "With Konro",
        "Without Konro",
        "Delta (abs)",
        "Delta (%)",
        "Direction",
    ]

    table_rows: List[List[str]] = []
    for name, w, wo, higher_better in rows:
        diff, pct = _delta(w, wo)
        if abs(diff) < 1e-12:
            direction = "same"
        elif (diff > 0 and higher_better) or (diff < 0 and not higher_better):
            direction = "better"
        else:
            direction = "worse"

        table_rows.append(
            [
                name,
                _fmt_val(w),
                _fmt_val(wo),
                f"{diff:+.6f}",
                _fmt_pct(pct),
                direction,
            ]
        )

    widths = [len(h) for h in headers]
    for r in table_rows:
        for i, c in enumerate(r):
            widths[i] = max(widths[i], len(c))

    def _line(cols: List[str]) -> str:
        return " | ".join(c.ljust(widths[i]) for i, c in enumerate(cols))

    sep = "-+-".join("-" * w for w in widths)

    print(_line(headers))
    print(sep)
    for r in table_rows:
        print(_line(r))


def _build_rows(with_data: Dict[str, Any], without_data: Dict[str, Any]) -> List[Tuple[str, float, float, bool]]:
    # (display_name, section, key, higher_is_better)
    specs = [
        ("proxy_mean", "proxy", "proxy_mean", True),
        ("proxy_ema", "proxy", "proxy_ema", True),
        ("below_target_ratio", "proxy", "below_target_ratio", False),
        ("delivery_ratio", "network", "delivery_ratio", True),
        ("drop_ratio", "network", "drop_ratio", False),
        ("latency_avg_s", "network", "latency_avg_s", False),
        ("latency_p95_s", "network", "latency_p95_s", False),
        ("stale_packets", "network", "stale_packets", False),
        ("underflow_packets", "network", "underflow_packets", False),
    ]

    rows: List[Tuple[str, float, float, bool]] = []
    for name, section, key, higher_better in specs:
        w = _get_num(with_data, section, key)
        wo = _get_num(without_data, section, key)
        rows.append((name, w, wo, higher_better))
    return rows


def _summary_score(rows: List[Tuple[str, float, float, bool]]) -> Tuple[int, int, int]:
    better = 0
    worse = 0
    same = 0
    for _, w, wo, higher_better in rows:
        diff = w - wo
        if abs(diff) < 1e-12:
            same += 1
        elif (diff > 0 and higher_better) or (diff < 0 and not higher_better):
            better += 1
        else:
            worse += 1
    return better, worse, same


def _plot_comparison(rows: List[Tuple[str, float, float, bool]], out_png: Path) -> None:
    if plt is None:
        raise RuntimeError(
            "matplotlib is not available in this environment. "
            "Install it with: pip install matplotlib"
        )

    labels = [r[0] for r in rows]
    with_vals = [r[1] for r in rows]
    without_vals = [r[2] for r in rows]

    x = list(range(len(labels)))
    width = 0.38

    fig, ax = plt.subplots(figsize=(14, 6))
    ax.bar([i - width / 2 for i in x], with_vals, width=width, label="With Konro")
    ax.bar([i + width / 2 for i in x], without_vals, width=width, label="Without Konro")

    ax.set_title("Konro vs Baseline: Metrics Comparison")
    ax.set_ylabel("Metric value")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=30, ha="right")
    ax.grid(axis="y", linestyle="--", linewidth=0.6, alpha=0.5)
    ax.legend()

    fig.tight_layout()
    out_png.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(str(out_png), dpi=180)
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Compare with/without Konro run summary JSON files"
    )
    parser.add_argument(
        "--with-konro",
        required=True,
        type=Path,
        help="Path to summary JSON generated with --konro_enable",
    )
    parser.add_argument(
        "--with-konro-run-index",
        default=-1,
        type=int,
        help="Run index to use if --with-konro points to a history JSON (default: -1 last run)",
    )
    parser.add_argument(
        "--without-konro",
        required=True,
        type=Path,
        help="Path to summary JSON generated without --konro_enable",
    )
    parser.add_argument(
        "--without-konro-run-index",
        default=-1,
        type=int,
        help="Run index to use if --without-konro points to a history JSON (default: -1 last run)",
    )
    parser.add_argument(
        "--out",
        default="",
        type=Path,
        help="Optional path to save comparison JSON",
    )
    parser.add_argument(
        "--plot-out",
        default="",
        type=Path,
        help="Optional path to save a PNG chart",
    )
    args = parser.parse_args()

    with_data = _select_run_entry(_read_json(args.with_konro), args.with_konro_run_index)
    without_data = _select_run_entry(_read_json(args.without_konro), args.without_konro_run_index)

    rows = _build_rows(with_data, without_data)
    _print_table(rows)

    better, worse, same = _summary_score(rows)
    print("\nOverall:")
    print(f"- Better metrics with Konro: {better}")
    print(f"- Worse metrics with Konro: {worse}")
    print(f"- Unchanged metrics: {same}")

    if args.out:
        comparison: Dict[str, Any] = {
            "with_konro": str(args.with_konro),
            "without_konro": str(args.without_konro),
            "metrics": [],
            "summary": {
                "better": better,
                "worse": worse,
                "same": same,
            },
        }

        for name, w, wo, higher_better in rows:
            diff, pct = _delta(w, wo)
            comparison["metrics"].append(
                {
                    "name": name,
                    "with_konro": w,
                    "without_konro": wo,
                    "delta_abs": diff,
                    "delta_pct": None if math.isinf(pct) else pct,
                    "higher_is_better": higher_better,
                }
            )

        args.out.parent.mkdir(parents=True, exist_ok=True)
        with args.out.open("w", encoding="utf-8") as f:
            json.dump(comparison, f, indent=2)
        print(f"\nComparison JSON written to: {args.out}")

    if args.plot_out:
        _plot_comparison(rows, args.plot_out)
        print(f"PNG chart written to: {args.plot_out}")


if __name__ == "__main__":
    main()
