[General]
network = CoPerceptionNetwork
cmdenv-express-mode = true
# Aumentiamo il limite a 24 ore (86400s) per evitare chiusure premature
sim-time-limit = 86400s 

# Sincronizzazione Real-Time: OMNeT++ andrà alla stessa velocità dell'orologio di sistema
scheduler-class = "cRealTimeScheduler"

# Configurazione Rete Wireless (802.11p per V2X)
*.radioMedium.typename = "Ieee80211ScalarRadioMedium"
*.radioMedium.backgroundNoise.power = -110dBm

# Configurazione Veicoli (Host)
*.numHosts = 6
*.host[*].mobility.typename = "PythonMobility"
*.host[*].mobility.initFromDisplayString = false
*.host[*].mobility.initialX = 0m
*.host[*].mobility.initialY = 0m
*.host[*].mobility.initialZ = 0m

# Configurazione NIC (Network Interface Card)
*.host[*].wlan[0].typename = "Ieee80211Interface"
*.host[*].wlan[0].radio.transmitter.power = 20mW
*.host[*].wlan[0].radio.receiver.sensitivity = -85dBm

# Configurazione App (CoPerceptionApp che creeremo)
*.host[*].numApps = 1
*.host[*].app[0].typename = "CoPerceptionApp"
*.host[*].app[0].localPort = 5000
*.host[*].app[0].destPort = 5000

# Configurazione Manager
*.manager.port = 5555
