[General]
network = CoPerceptionNetwork
cmdenv-express-mode = false

# Qui decidi il ritardo!
*.manager.delay = uniform(0.01s, 0.2s)   # Metti 0.1s, 0.5s, o anche formule random!
*.manager.packetLoss = 0.1               # Metti 0.0, 0.1, 0.3, 0.5 (0.5 = 50% di pacchetti persi)